create table if not exists public.child_attendance (
  id bigint generated by default as identity primary key,
  child_id text not null,
  attendance_date date not null,
  status text not null check (status in ('Present', 'Late', 'Absent', 'Excused')),
  source text not null default 'teacher',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (child_id, attendance_date)
);

create table if not exists public.parent_announcements (
  id bigint generated by default as identity primary key,
  parent_id text not null,
  child_id text,
  title text not null,
  message text not null,
  is_published boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.child_attendance enable row level security;
alter table public.parent_announcements enable row level security;

drop policy if exists "app child attendance access" on public.child_attendance;
create policy "app child attendance access" on public.child_attendance for all using (true) with check (true);
drop policy if exists "app parent announcements access" on public.parent_announcements;
create policy "app parent announcements access" on public.parent_announcements for all using (true) with check (true);
